[package]
name = "cjdns_sys"
version = "0.1.0"
authors = ["Caleb James DeLisle <cjd@cjdns.fr>"]
edition = "2018"
build = "build.rs"

[dependencies]
sodiumoxide = { git = "https://github.com/cjdelisle/sodiumoxide", rev = "76dc0e6e587b8c8a4bb193ebba9f8ae8f090b81b", default-features = false, features = ["std"] }
libuv-sys2 = { git = "https://github.com/cjdelisle/libuv-sys", rev = "dc3c3427fa7f4f9f6781ab462478ca5de97d577c", default-features = false, features = ["no-bindings","with-headers"] }
thiserror = "1.0"
anyhow = "1.0"

[build_dependencies]
cc = "1.0"
anyhow = "1.0"
cbindgen = { version = "0.15", optional = true }
bindgen = { version = "0.55", optional = true }

[features]
generate-rffi = ["cbindgen"]
generate-cffi = ["bindgen"]